# Hugo site configuration for Blowfish (Git submodule install)
# Using theme directory, so set `theme = "blowfish"` here

theme = "blowfish"
baseURL = "/"
defaultContentLanguage = "zh-cn"
enableRobotsTXT = true
summaryLength = 0

enableEmoji = true

googleAnalytics = "G-DHLCW2VY08"

[pagination]
  pagerSize = 10

[imaging]
  anchor = "Center"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "categories"
    weight = 100

  [[related.indices]]
    name = "series"
    weight = 50

  [[related.indices]]
    name = "authors"
    weight = 20

  [[related.indices]]
    name = "date"
    weight = 10

  [[related.indices]]
    applyFilter = false
    name = "fragmentrefs"
    type = "fragments"
    weight = 10

