[[main]]
  name = "首页"
  pageRef = "/"
  weight = 1

[[main]]
  name = "博文"
  pageRef = "post"
  weight = 10

[[main]]
  name = "文档"
  pageRef = "docs"
  weight = 20

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 30

# [[footer]]
#   name = "标签"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "分类"
#   pageRef = "categories"
#   weight = 20

