colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true

enableA11y = false
enableSearch = true
enableCodeCopy = false

# TechAI8 主要内容区块
mainSections = ["news", "reviews", "rankings", "guides", "tutorials", "topics", "resources"]

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 5
  showMoreLink = false
  showMoreLinkDest = "/news/"
  cardView = false
  cardViewScreenWidth = false

[article]
  showDate = true
  showAuthor = true
  showHero = false
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = false
  showTaxonomies = false
  showCategoryOnly = false
  showAuthorsBadges = false
  showWordCount = true

[list]
  showHero = false
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = false
  orderByWeight = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

# AdSense 配置 (生产环境时填入真实值)
[adsense]
  publisher_id = "ca-pub-XXXXXXXXXX"  # 替换为真实的 AdSense Publisher ID
  [adsense.slots]
    in_article = "1234567890"         # 文章内广告位 ID
    sidebar = "1234567891"            # 侧边栏广告位 ID
    list_page = "1234567892"          # 列表页广告位 ID
    mobile_sticky = "1234567893"      # 移动端粘性广告位 ID
    default = "1234567894"            # 默认广告位 ID

# TechAI8 特定配置
[techai8]
  # 数字记者配置
  enableReactions = true
  enableComparisons = true
  enableAIDisclosure = true

  # 内容质量配置
  [techai8.quality]
    minSources = 2
    requireOfficialSource = true
    enableFactCheck = true

  # 多语言配置
  [techai8.multilingual]
    enableHreflang = true
    enableAutoTranslate = false
    defaultRegion = "Global"

